FROM python:3.12-alpine

EXPOSE 8000

WORKDIR /app 

COPY ./requirements.txt .
COPY . .

RUN pip install -r ./requirements.txt
RUN python manage.py migrate

CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]